"""add job description and resume text

Revision ID: 5c2c14c790f4
Revises: ae391250d270
Create Date: 2026-10-06 11:49:56.292518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2c14c790f4'
down_revision: Union[str, Sequence[str], None] = 'ae391250d270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('resume_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'resume_text')
    op.drop_column('jobs', 'job_description')
    # ### end Alembic commands ###
